const SYSTEM_ROOM_TYPE = -1
const STANDARD_ROOM_TYPE = 0
const REALTIME_ROOM_TYPE = 1
const TURNBASED_ROOM_TYPE = 2

module.exports = {
	SYSTEM_ROOM_TYPE,
	STANDARD_ROOM_TYPE,
	REALTIME_ROOM_TYPE,
	TURNBASED_ROOM_TYPE
}
